services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883" # MQTT 端口
      - "9001:9001" # WebSocket 端口
    volumes:
      - ./config:/mosquitto/config
      - ./db:/mosquitto/data
      - ./log:/mosquitto/log
