services:
  postgres:
    image: postgres:latest
    restart: no
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=homestead
      - POSTGRES_DB=homestead
