services:
  rdb:
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    ports:
      - "6379:6379"
    volumes:
      - ./db:/root/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf # 绑定 redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
